gml_Object_o07__Game_Create_0:
  - type: prepend
    code: |-
      rescue = false;
      rescueX = 2064;
      rescueY = 944;
      rescueRoom = rm07_GravGuns;
      rescueTimer = 0;
      RESCUE_TIME = 300;

gml_GlobalScript_scr07_CalculateCompletionPercentage:
  - type: findreplace
    find: |-
      var _percentItems = floor((ds_list_size(o07__Game.upgradeCollected) / global.g07_totalCollectibleCount) * 100);
    code: |-
      var upgradeCount = 0;
      for (var i = 0; i <= 13; i++)
      {
        if (is_location_collected(i))
            upgradeCount++;
      }
      for (var i = 100; i <= 111; i++)
      {
        if (is_location_collected(i))
            upgradeCount++;
      }
      for (var i = 200; i <= 213; i++)
      {
        if (is_location_collected(i))
            upgradeCount++;
      }
      if (is_location_collected(300))
        upgradeCount++;
      var _percentItems = floor((upgradeCount / global.g07_totalCollectibleCount) * 100);
